package yingka_sdk

// Command Constants
const (
	CMD_GET_KEY                = 0x01
	CMD_AI_WAKEUP              = 0x02
	CMD_SIMULTANEOUS_TRANSLATE = 0x03
	CMD_MEETING_ASSISTANT      = 0x04
	CMD_AI_PHOTO_RECOGNIZE     = 0x05
	CMD_SYNC_FILE_1            = 0x06
	CMD_SYNC_FILE_2            = 0x07
	CMD_SYNC_FILE_3            = 0x08
	CMD_GET_BT_STATUS          = 0x09
	CMD_GET_CONNECTED_NAME     = 0x0A
	CMD_NEW_FILE_NOTIFY        = 0x0B
	CMD_SYNC_TIME              = 0x0F
	CMD_LIVE_MODE_1            = 0x10
	CMD_LIVE_MODE_2            = 0x11
	CMD_LIVE_MODE_3            = 0x12
	CMD_DEV_TRIGGER_PHOTO      = 0x13
	CMD_VOICE_RECOG_SWITCH     = 0x14
	CMD_SYNC_BATTERY           = 0x15
	CMD_VIDEO_DURATION         = 0x16
	CMD_GET_DEV_STATUS         = 0x17
	CMD_CONTROL_MEDIA          = 0x18
	CMD_DEV_REPORT_STATUS      = 0x19
	CMD_SYNC_LANGUAGE          = 0x1A
	CMD_GET_DEV_INFO           = 0x1B
)

// Common Status Constants
const (
	STATUS_START   = 0x01
	STATUS_STOP    = 0x02
	STATUS_SUCCESS = 0x01
	STATUS_FAIL    = 0x02
)

// AI Status (0x02)
const (
	AI_STATUS_START_SUCCESS = 0x01
	AI_STATUS_START_FAIL    = 0x02
	AI_STATUS_MIC_TRANSMIT  = 0x03
	AI_STATUS_MIC_END       = 0x04
	AI_STATUS_APP_END_MIC   = 0x05
	AI_STATUS_APP_END_AI    = 0x06
)

// Photo Recognize Status (0x05 / 0x13)
const (
	PHOTO_STATUS_READY         = 0x03
	PHOTO_STATUS_NOT_READY     = 0x04
	PHOTO_STATUS_TRANSMITTING  = 0x05
	PHOTO_STATUS_TRANSMIT_END  = 0x06
	PHOTO_STATUS_RECEIVE_OK    = 0x07
	PHOTO_STATUS_DEV_SEND_DESC = 0x01
	PHOTO_STATUS_APP_DESC_OK   = 0x01
	PHOTO_STATUS_APP_DESC_FAIL = 0x02
	PHOTO_STATUS_ERROR         = 0x02
)

// Wifi Mode (0x06 / 0x10)
const (
	WIFI_MODE_AP  = 0x01
	WIFI_MODE_P2P = 0x02
)

// Device State (0x17)
const (
	DEV_STATE_IDLE  = 0x00
	DEV_STATE_PHOTO = 0x01
	DEV_STATE_VIDEO = 0x02
	DEV_STATE_AUDIO = 0x03
)

// Media Control (0x18)
const (
	MEDIA_CTRL_PHOTO       = 0x01
	MEDIA_CTRL_VIDEO_START = 0x02
	MEDIA_CTRL_VIDEO_STOP  = 0x03
	MEDIA_CTRL_AUDIO_START = 0x04
	MEDIA_CTRL_AUDIO_STOP  = 0x05
)

// Device Report Status (0x19)
const (
	REPORT_PHOTO_START = 0x01
	REPORT_PHOTO_END   = 0x02
	REPORT_VIDEO_START = 0x03
	REPORT_VIDEO_END   = 0x04
	REPORT_AUDIO_START = 0x05
	REPORT_AUDIO_END   = 0x06
)

// Language (0x1A)
const (
	LANG_CHINESE = 0x01
	LANG_ENGLISH = 0x02
)

const (
	FIXED_HEADER = 0xFF
)
